# PolicyLM-guided MCTS agent

type: mcts

node_type: holophrasm
max_mcts_nodes: 1000
expansions: 1000
max_searches: 1
max_examples: 1000
val_search_budget: 10000

policy:
    type: LM
    lr: 1e-4
    mu: 0.0
    ratio_conditioning: False
    mu_warmup: True
    mu_warmup_steps: 100
    mu_cooldown: False
    mu_cooldown_type: linear
    skip_conj_prefix_loss: True
    # FIXME(f.srambical): these are arbitrary values; update these two values before pushing
    threshold: 0.2
    value_prior_weight: 10
    max_pos_neg_ratio: 5
    train_iterations: 2000
    batch_size: 10000
    total_iterations: 5

defaults:
    - _self_
    - curiosity: constant
